# commands to specify testing environments
language: python
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
    - python: 3.8
      dist: xenial
      sudo: true
    - python: 3.9
      dist: xenial
      sudo: true
    - python: nightly
      dist: xenial
      sudo: true
  allow_failures:
    - python: nightly

branches:
  only:
    - master
    - /^[0-9].+$/

# command to install dependencies
install:
  - pip install -r test-requirements.txt

# command to run tests
script:
  python -m unittest discover
