package:
  name: 'nionswift-experimental-tools'
  version: '0.3.0'

source:
  git_rev: 0.3.0
  git_url: https://github.com/nion-software/experimental.git

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  include_recipe: False

requirements:
  host:
    - python
    - setuptools
  run:
    - python >=3.5

test:
  imports:
    - nionswift_plugin.nion_experimental_tools

about:
  home: https://github.com/nion-software/experimental
  summary: "Useful experimental tools for Nion Swift."
  description: "Useful experimental tools for Nion Swift."

extra:
  recipe-maintainers:
    cmeyer
