package:
  name: 'nionswift-experimental'
  version: '0.7.7'

source:
  git_rev: 0.7.7
  git_url: https://github.com/nion-software/experimental.git

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  include_recipe: False

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python >=3.8
    - nionswift >=0.15.0,<0.17.0
    - nionui >=0.6.3,<0.7.0

test:
  imports:
    - nionswift_plugin.nion_experimental_tools

about:
  home: https://github.com/nion-software/experimental
  summary: "Experimental tools for Nion Swift."
  description: "Experimental tools for Nion Swift."

extra:
  recipe-maintainers:
    cmeyer
